### ISSUE TITLE
org-mode page not show in the Cardbox

### ISSUE THREAD

**Issue by saccohuo** [sosuisen/logseq-cardbox#1]
There is no org-mode page show in the Cardbox in the Cardbox.

OS: Windows 10
Logseq version: 0.9.20
page type: org-mode

**Comment by sosuisen** [comment]
I am very grateful for your report!

I didn't notice it because I am not an org-mode user. I will implement this in the next version.

**Comment by sosuisen** [comment]
Solved in v0.1.6.  Please "Check update" on your Logseq for this plugin.
